name: vae_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.6.1
  - torchvision>=0.10.1
  - PyYAML==6.0
  - pip
  - pip:
    - pytorch-lightning>=1.6.0
    - tensorboard>=2.2.0
    - torchsummary==1.5.1 